# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# os
os:
  - linux

# Set the python version to 3.6, 3.7
python:
  - "3.5"
  - "3.6"
  - "3.7"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 47bffd97-db08-4bf5-a0e3-7ea1c8cb86c0
# Install the pip dependency
install:
  - pip install sentencepiece
  - pip install gensim
  - pip install nltk
  - pip install numpy
  - pip install scipy
  - pip install sklearn-crfsuite

# Run the unit test
script:
  - python test.py
  # - coverage run tests.py
